#!/usr/bin/env python3
"""
Main154.py
Phase 9 — Experiment 34:
STRICT OOF MAIN133 REPRESENTATION + MAIN115 SPECIALIST FUSION

Goal
----
Validate the promising Exp28/Main148 idea without validation leakage.

Inputs:
  1) Main133 / Exp13 learned 128-D representation.
  2) Main115 five specialist OOF probabilities.

Training-side protocol:
  - Canonical split is preserved exactly.
  - Main115 OOF probabilities are loaded from main115_results.npz.
  - Main133 embeddings for the canonical training split are generated by
    5-fold strict cross-fitting:
        * vocabulary fit only on fold-train
        * TF-IDF fit only on fold-train
        * SVD fit only on fold-train
        * structural scaler fit only on fold-train
        * neural model trained only on fold-train
        * held-out fold receives the resulting latent z
  - The fold model is trained for a fixed 3 epochs. The held-out fold is
    NEVER used for model selection/early stopping.

Validation-side protocol:
  - Reconstruct the exact saved Main133 validation z from main133_best.pt.
  - Require max absolute reconstruction error < 1e-5.
  - Train LR/SVM on the strict OOF fusion matrix.
  - Evaluate once on the untouched canonical validation set.

IMPORTANT
---------
This script deliberately does NOT use the 94.2125% Exp28 validation-fitted
fusion result as evidence of submit-safe performance.

No Kaggle submission.
"""

import json
import random
import time
from pathlib import Path
import importlib.util

import numpy as np
import torch
import torch.nn as nn

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV


ROOT = Path("/home/manu/Desktop/ML4CPMS/project_1")
TRAIN_PATH = ROOT / "train.json"
MAIN133_CHECKPOINT = ROOT / "main133_best.pt"
MAIN133_EMBEDDINGS = ROOT / "main133_embeddings.npz"
MAIN115_RESULTS = ROOT / "main115_results.npz"

SEED = 154
N_SPLITS = 5
FOLD_EPOCHS = 3
BATCH = 64
MAXLEN = 384

# Main133 architecture/configuration.
TOKEN_EMBED = 96
TOKEN_HIDDEN = 96
TFIDF_DIM = 256
TFIDF_HIDDEN = 128
STRUCT_HIDDEN = 96
LATENT = 128
FUSION_HIDDEN = 256
LR = 2e-3
WEIGHT_DECAY = 1e-4

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def seed_all(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_json_or_jsonl(path):
    raw = path.read_text(encoding="utf-8").strip()
    try:
        obj = json.loads(raw)
        if isinstance(obj, list):
            return obj
        if isinstance(obj, dict):
            for key in ("train", "data", "records", "documents"):
                if key in obj and isinstance(obj[key], list):
                    return obj[key]
    except json.JSONDecodeError:
        pass

    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def label_to_int(v):
    if isinstance(v, (int, np.integer)):
        return int(v)
    s = str(v).strip().upper()
    if s == "A":
        return 0
    if s == "B":
        return 1
    return int(v)


def tokens_to_string(tokens):
    return " ".join(map(str, tokens))


def load_main133_module():
    """
    Reuse the exact Main133 implementation for structural_features and
    MultiInputModel. This avoids silently changing the architecture.
    """
    candidates = [
        ROOT / "main133.py",
        ROOT / "main133(1).py",
    ]
    path = next((p for p in candidates if p.exists()), None)
    if path is None:
        raise FileNotFoundError(
            "Could not find main133.py or main133(1).py in project directory."
        )

    spec = importlib.util.spec_from_file_location("main133_reference", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def encode_sequences(seqs, vocab, maxlen):
    arr = np.zeros((len(seqs), maxlen), dtype=np.int64)
    for i, seq in enumerate(seqs):
        ids = [vocab.get(t, 1) for t in seq[:maxlen]]
        if ids:
            arr[i, :len(ids)] = ids
    return arr


def batched_indices(n, batch, rng):
    idx = np.arange(n)
    rng.shuffle(idx)
    for s in range(0, n, batch):
        yield idx[s:s + batch]


def build_fold_features(token_lists, fit_idx, query_idx, main133):
    """
    Fit every preprocessing object on fit_idx only.
    Return token ids, SVD TF-IDF, and scaled structural features for query_idx.
    """
    fit_tokens = [token_lists[i] for i in fit_idx]
    query_tokens = [token_lists[i] for i in query_idx]

    vocab = main133.make_vocab(fit_tokens)
    vocab_size = max(vocab.values(), default=1) + 1

    x_tokens = encode_sequences(query_tokens, vocab, MAXLEN)

    fit_text = [tokens_to_string(s) for s in fit_tokens]
    query_text = [tokens_to_string(s) for s in query_tokens]

    tfidf = main133.TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\S+",
        ngram_range=(1, 3),
        min_df=2,
        max_df=0.995,
        max_features=60000,
        sublinear_tf=True,
        dtype=np.float32,
    )
    x_tfidf_fit = tfidf.fit_transform(fit_text)
    x_tfidf_query = tfidf.transform(query_text)

    svd = TruncatedSVD(n_components=TFIDF_DIM, random_state=SEED)
    x_svd_fit = svd.fit_transform(x_tfidf_fit).astype(np.float32)
    x_svd_query = svd.transform(x_tfidf_query).astype(np.float32)

    x_struct_fit = np.stack(
        [main133.structural_features(s) for s in fit_tokens]
    )
    x_struct_query = np.stack(
        [main133.structural_features(s) for s in query_tokens]
    )

    scaler = StandardScaler()
    x_struct_fit = scaler.fit_transform(x_struct_fit).astype(np.float32)
    x_struct_query = scaler.transform(x_struct_query).astype(np.float32)

    return (
        x_tokens,
        x_svd_fit,
        x_svd_query,
        x_struct_fit,
        x_struct_query,
        vocab_size,
    )


def train_fold_and_predict(
    token_lists,
    y,
    fit_idx,
    hold_idx,
    main133,
    fold_number,
):
    """
    Strict fold training.

    The holdout fold is used ONLY to obtain held-out latent vectors after
    training. It is not used for early stopping or model selection.
    """
    (
        x_tokens_hold,
        _x_svd_fit_unused,
        x_svd_hold,
        _x_struct_fit_unused,
        x_struct_hold,
        vocab_size,
    ) = build_fold_features(
        token_lists, fit_idx, hold_idx, main133
    )

    # Rebuild fit-side features separately because build_fold_features above
    # intentionally returns only query-side token IDs/SVD/structural arrays.
    fit_tokens = [token_lists[i] for i in fit_idx]
    hold_tokens = [token_lists[i] for i in hold_idx]

    vocab = main133.make_vocab(fit_tokens)
    x_tokens_fit = encode_sequences(fit_tokens, vocab, MAXLEN)

    fit_text = [tokens_to_string(s) for s in fit_tokens]
    tfidf = main133.TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\S+",
        ngram_range=(1, 3),
        min_df=2,
        max_df=0.995,
        max_features=60000,
        sublinear_tf=True,
        dtype=np.float32,
    )
    x_tfidf_fit = tfidf.fit_transform(fit_text)
    svd = TruncatedSVD(n_components=TFIDF_DIM, random_state=SEED)
    x_svd_fit = svd.fit_transform(x_tfidf_fit).astype(np.float32)

    x_struct_fit = np.stack(
        [main133.structural_features(s) for s in fit_tokens]
    )
    scaler = StandardScaler()
    x_struct_fit = scaler.fit_transform(x_struct_fit).astype(np.float32)

    model = main133.MultiInputModel(vocab_size, pad_id=0).to(DEVICE)

    y_fit = y[fit_idx].astype(np.float32)
    class0 = float((y_fit == 0).sum())
    class1 = float((y_fit == 1).sum())
    pos_weight = torch.tensor(
        [class1 / max(class0, 1.0)], device=DEVICE
    )

    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LR,
        weight_decay=WEIGHT_DECAY,
    )

    xt = torch.from_numpy(x_tokens_fit)
    xf = torch.from_numpy(x_svd_fit)
    xs = torch.from_numpy(x_struct_fit)
    yt = torch.from_numpy(y_fit)

    rng = np.random.default_rng(SEED + fold_number)

    model.train()
    for epoch in range(1, FOLD_EPOCHS + 1):
        total_loss = 0.0

        for bi in batched_indices(len(fit_idx), BATCH, rng):
            tb = xt[bi].to(DEVICE)
            fb = xf[bi].to(DEVICE)
            sb = xs[bi].to(DEVICE)
            yb = yt[bi].to(DEVICE)

            optimizer.zero_grad(set_to_none=True)
            logits, _ = model(tb, fb, sb)
            loss = criterion(logits, yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

            total_loss += float(loss.item()) * len(bi)

        print(
            f"Fold {fold_number} | epoch {epoch}/{FOLD_EPOCHS} | "
            f"train loss {total_loss / len(fit_idx):.5f}"
        )

    # Held-out latent only after fold training is complete.
    model.eval()
    xtq = torch.from_numpy(x_tokens_hold)
    xfq = torch.from_numpy(x_svd_hold)
    xsq = torch.from_numpy(x_struct_hold)

    z_parts = []
    with torch.no_grad():
        for s in range(0, len(hold_idx), BATCH):
            _, z = model(
                xtq[s:s+BATCH].to(DEVICE),
                xfq[s:s+BATCH].to(DEVICE),
                xsq[s:s+BATCH].to(DEVICE),
            )
            z_parts.append(z.cpu().numpy())

    return np.concatenate(z_parts).astype(np.float32)


def reconstruct_exact_main133_validation(
    token_lists,
    va_idx,
    checkpoint,
    main133_module,
):
    """
    Reproduce the saved Main133 validation latent.

    Main133's saved checkpoint contains the exact vocabulary, TF-IDF
    vocabulary/IDF, SVD components, structural scaler, and neural weights.
    We therefore do NOT fit a new TF-IDF model here.

    The sparse TF-IDF arithmetic is reproduced directly:
        raw counts
        -> sublinear TF = 1 + log(count)
        -> saved IDF
        -> L2 row normalization
        -> saved SVD projection

    This is intentionally strict because the reconstructed latent must match
    the previously saved Main133 validation latent to < 1e-5.
    """
    rows = [token_lists[i] for i in va_idx]
    texts = [tokens_to_string(s) for s in rows]

    saved_vocab = checkpoint["tfidf_vocabulary"]
    saved_idf = np.asarray(checkpoint["tfidf_idf"], dtype=np.float32)
    saved_svd = np.asarray(
        checkpoint["svd_components"], dtype=np.float32
    )

    cv = CountVectorizer(
        vocabulary=saved_vocab,
        token_pattern=r"(?u)\S+",
        ngram_range=(1, 3),
        dtype=np.float32,
    )

    X = cv.transform(texts).tocoo(copy=True)

    # Main133 used sublinear_tf=True.
    X.data = (1.0 + np.log(X.data)).astype(np.float32)

    # Apply Main133's exact saved IDF.
    X.data *= saved_idf[X.col]

    X = X.tocsr()

    # L2 normalization, matching sklearn's TfidfTransformer convention.
    row_norm = np.sqrt(X.multiply(X).sum(axis=1)).A1
    inv_norm = np.divide(
        1.0,
        row_norm,
        out=np.zeros_like(row_norm),
        where=row_norm > 0,
    )
    X = X.multiply(inv_norm[:, None]).tocsr()

    X_svd = (X @ saved_svd.T).astype(np.float32)

    # Structural features and saved StandardScaler parameters.
    X_struct = np.stack(
        [main133_module.structural_features(s) for s in rows]
    ).astype(np.float32)

    struct_mean = np.asarray(
        checkpoint["struct_scaler_mean"], dtype=np.float32
    )
    struct_scale = np.asarray(
        checkpoint["struct_scaler_scale"], dtype=np.float32
    )
    X_struct = (
        (X_struct - struct_mean) / struct_scale
    ).astype(np.float32)

    # Raw-token representation uses the exact saved Main133 token vocabulary.
    token_vocab = checkpoint["vocab"]
    X_tokens = encode_sequences(
        rows,
        token_vocab,
        MAXLEN,
    )

    vocab_size = max(token_vocab.values(), default=1) + 1
    model = main133_module.MultiInputModel(
        vocab_size,
        pad_id=0,
    ).to(DEVICE)

    model.load_state_dict(checkpoint["state_dict"])
    model.eval()

    zs = []
    logits = []

    with torch.no_grad():
        for s in range(0, len(rows), BATCH):
            tb = torch.from_numpy(X_tokens[s:s+BATCH]).to(DEVICE)
            fb = torch.from_numpy(X_svd[s:s+BATCH]).to(DEVICE)
            sb = torch.from_numpy(X_struct[s:s+BATCH]).to(DEVICE)

            lg, zz = model(tb, fb, sb)
            logits.append(lg.cpu().numpy())
            zs.append(zz.cpu().numpy())

    return (
        np.concatenate(zs).astype(np.float32),
        np.concatenate(logits).astype(np.float32),
    )

def main():
    seed_all(SEED)
    t0 = time.time()

    print("=" * 78)
    print("MAIN154 — STRICT OOF MAIN133 + MAIN115 FUSION")
    print("=" * 78)
    print("Device:", DEVICE)

    for p in (TRAIN_PATH, MAIN133_CHECKPOINT, MAIN133_EMBEDDINGS, MAIN115_RESULTS):
        if not p.exists():
            raise FileNotFoundError(f"Missing required artifact: {p}")

    main133 = load_main133_module()
    print("Loaded Main133 reference implementation.")

    rows = load_json_or_jsonl(TRAIN_PATH)
    token_lists = [list(r["text"]) for r in rows]
    y = np.asarray(
        [label_to_int(r.get("label", r.get("target", r.get("y")))) for r in rows],
        dtype=np.int64,
    )

    n = len(y)
    all_idx = np.arange(n)

    tr_idx, va_idx = train_test_split(
        all_idx,
        test_size=0.20,
        stratify=y,
        random_state=42,
    )

    print("Dataset:", n)
    print("Canonical train/validation:", len(tr_idx), len(va_idx))
    print("Canonical validation order preserved: YES")

    # ------------------------------------------------------------------
    # Load Main115 OOF/validation specialist outputs.
    # ------------------------------------------------------------------
    main115 = np.load(MAIN115_RESULTS, allow_pickle=True)

    required = {
        "y_oof",
        "y_val",
        "specialist_p_oof",
        "specialist_p_val",
    }
    missing = sorted(required - set(main115.files))
    if missing:
        raise KeyError(
            f"main115_results.npz is missing required arrays: {missing}"
        )

    y115_oof = main115["y_oof"].astype(np.int64)
    y115_val = main115["y_val"].astype(np.int64)
    p115_oof = main115["specialist_p_oof"].astype(np.float32)
    p115_val = main115["specialist_p_val"].astype(np.float32)

    if p115_oof.shape != (len(tr_idx), 5):
        raise ValueError(
            f"Expected Main115 OOF shape {(len(tr_idx), 5)}, "
            f"got {p115_oof.shape}"
        )
    if p115_val.shape != (len(va_idx), 5):
        raise ValueError(
            f"Expected Main115 VAL shape {(len(va_idx), 5)}, "
            f"got {p115_val.shape}"
        )

    if not np.array_equal(y115_oof, y[tr_idx]):
        raise RuntimeError(
            "FAIL: Main115 OOF labels do not exactly match canonical "
            "training split order."
        )

    if not np.array_equal(y115_val, y[va_idx]):
        raise RuntimeError(
            "FAIL: Main115 validation labels do not exactly match canonical "
            "validation split order."
        )

    print("Main115 OOF alignment: PASS")
    print("Main115 VAL alignment: PASS")

    # ------------------------------------------------------------------
    # Exact Main133 validation reconstruction safety check.
    # ------------------------------------------------------------------
    checkpoint = torch.load(
        MAIN133_CHECKPOINT,
        map_location="cpu",
        weights_only=False,
    )

    saved = np.load(MAIN133_EMBEDDINGS, allow_pickle=True)
    saved_va_idx = saved["val_indices"].astype(np.int64)
    saved_z_val = saved["z_val"].astype(np.float32)

    if not np.array_equal(saved_va_idx, va_idx):
        raise RuntimeError(
            "FAIL: saved Main133 validation indices do not match canonical "
            "validation order."
        )

    print("\nReconstructing exact Main133 validation latent...")
    z_val_exact, _ = reconstruct_exact_main133_validation(
        token_lists, va_idx, checkpoint, main133
    )

    max_diff = float(np.max(np.abs(z_val_exact - saved_z_val)))
    mean_diff = float(np.mean(np.abs(z_val_exact - saved_z_val)))

    print("Main133 z_val max abs diff :", max_diff)
    print("Main133 z_val mean abs diff:", mean_diff)
    print("Safety tolerance           : 1e-5")

    if max_diff >= 1e-5:
        raise RuntimeError(
            "FAIL: Main133 validation reconstruction exceeds 1e-5. "
            "Do not continue to fusion."
        )

    print("Main133 validation reconstruction: PASS")

    # ------------------------------------------------------------------
    # Strict OOF Main133 training embeddings.
    # ------------------------------------------------------------------
    z_oof = np.zeros((len(tr_idx), LATENT), dtype=np.float32)
    filled = np.zeros(len(tr_idx), dtype=bool)

    skf = StratifiedKFold(
        n_splits=N_SPLITS,
        shuffle=True,
        random_state=SEED,
    )

    y_train_canonical = y[tr_idx]

    print("\nStarting strict 5-fold Main133 OOF generation...")
    for fold_no, (fit_pos, hold_pos) in enumerate(
        skf.split(np.zeros(len(tr_idx)), y_train_canonical),
        start=1,
    ):
        fit_idx = tr_idx[fit_pos]
        hold_idx = tr_idx[hold_pos]

        print("\n" + "-" * 70)
        print(
            f"FOLD {fold_no}/{N_SPLITS} | "
            f"fit={len(fit_idx)} holdout={len(hold_idx)}"
        )

        z_hold = train_fold_and_predict(
            token_lists,
            y,
            fit_idx,
            hold_idx,
            main133,
            fold_no,
        )

        if z_hold.shape != (len(hold_pos), LATENT):
            raise RuntimeError(
                f"Unexpected fold latent shape: {z_hold.shape}"
            )

        z_oof[hold_pos] = z_hold
        filled[hold_pos] = True

    if not np.all(filled):
        raise RuntimeError("FAIL: not all OOF rows were filled.")

    print("\nStrict Main133 OOF generation: PASS")
    print("z_oof shape:", z_oof.shape)

    # ------------------------------------------------------------------
    # Fusion matrix: strict OOF training side.
    # ------------------------------------------------------------------
    x_oof = np.concatenate([z_oof, p115_oof], axis=1)
    x_val = np.concatenate([z_val_exact, p115_val], axis=1)

    print("Fusion train shape:", x_oof.shape)
    print("Fusion validation shape:", x_val.shape)

    # ------------------------------------------------------------------
    # Fixed, non-tuned LR fusion.
    # ------------------------------------------------------------------
    print("\n=== STRICT OOF LOGISTIC REGRESSION FUSION ===")
    lr_model = LogisticRegression(
        C=0.1,
        max_iter=3000,
        class_weight="balanced",
        random_state=SEED,
    )
    lr_model.fit(x_oof, y_train_canonical)

    lr_oof_prob = lr_model.predict_proba(x_oof)[:, 1]
    lr_val_prob = lr_model.predict_proba(x_val)[:, 1]

    lr_oof_acc = accuracy_score(
        y_train_canonical, lr_oof_prob >= 0.5
    )
    lr_oof_auc = roc_auc_score(
        y_train_canonical, lr_oof_prob
    )
    lr_val_acc = accuracy_score(
        y[va_idx], lr_val_prob >= 0.5
    )
    lr_val_auc = roc_auc_score(
        y[va_idx], lr_val_prob
    )

    print("OOF accuracy:", lr_oof_acc)
    print("OOF AUC     :", lr_oof_auc)
    print("VAL accuracy:", lr_val_acc)
    print("VAL AUC     :", lr_val_auc)

    # ------------------------------------------------------------------
    # Fixed linear SVM fusion, calibrated only after OOF fitting.
    # The calibration itself uses only the OOF training matrix.
    # ------------------------------------------------------------------
    print("\n=== STRICT OOF LINEAR SVM FUSION ===")
    svm_base = LinearSVC(
        C=1.0,
        class_weight="balanced",
        random_state=SEED,
        max_iter=5000,
    )
    svm_model = CalibratedClassifierCV(
        estimator=svm_base,
        method="sigmoid",
        cv=5,
    )
    svm_model.fit(x_oof, y_train_canonical)

    svm_oof_prob = svm_model.predict_proba(x_oof)[:, 1]
    svm_val_prob = svm_model.predict_proba(x_val)[:, 1]

    svm_oof_acc = accuracy_score(
        y_train_canonical, svm_oof_prob >= 0.5
    )
    svm_oof_auc = roc_auc_score(
        y_train_canonical, svm_oof_prob
    )
    svm_val_acc = accuracy_score(
        y[va_idx], svm_val_prob >= 0.5
    )
    svm_val_auc = roc_auc_score(
        y[va_idx], svm_val_prob
    )

    print("OOF accuracy:", svm_oof_acc)
    print("OOF AUC     :", svm_oof_auc)
    print("VAL accuracy:", svm_val_acc)
    print("VAL AUC     :", svm_val_auc)

    # ------------------------------------------------------------------
    # Compare directly against frozen Main115 reference.
    # ------------------------------------------------------------------
    main115_frozen = np.mean(p115_val, axis=1)
    main115_mean_acc = accuracy_score(
        y[va_idx], main115_frozen >= 0.5
    )
    main115_mean_auc = roc_auc_score(
        y[va_idx], main115_frozen
    )

    main115_frozen_rule = (
        (np.sum(p115_val >= 0.5, axis=1) >= 3).astype(np.int64)
    )
    main115_rule_acc = accuracy_score(
        y[va_idx], main115_frozen_rule
    )

    print("\n=== MAIN115 REFERENCES ===")
    print("Specialist mean VAL accuracy:", main115_mean_acc)
    print("Specialist mean VAL AUC     :", main115_mean_auc)
    print("Frozen consensus VAL accuracy:", main115_rule_acc)

    print("\n=== MAIN154 SUMMARY ===")
    print(f"LR  strict OOF fusion VAL accuracy : {lr_val_acc:.6f}")
    print(f"LR  strict OOF fusion VAL AUC      : {lr_val_auc:.6f}")
    print(f"SVM strict OOF fusion VAL accuracy : {svm_val_acc:.6f}")
    print(f"SVM strict OOF fusion VAL AUC      : {svm_val_auc:.6f}")
    print(f"Main115 frozen rule VAL accuracy   : {main115_rule_acc:.6f}")

    report = {
        "experiment": "Main154 / Phase9 Exp34",
        "description": (
            "Strict 5-fold OOF fusion of Main133 learned representation "
            "with Main115 specialist probabilities."
        ),
        "seed": SEED,
        "device": str(DEVICE),
        "dataset_size": int(n),
        "canonical_train_size": int(len(tr_idx)),
        "canonical_val_size": int(len(va_idx)),
        "canonical_split": {
            "method": "train_test_split",
            "test_size": 0.20,
            "stratify": True,
            "random_state": 42,
            "order_preserved": True,
        },
        "strict_ooo": {
            "folds": N_SPLITS,
            "fold_seed": SEED,
            "main133_fold_epochs": FOLD_EPOCHS,
            "main133_fit_only_on_fold_train": True,
            "main115_source": "main115_results.npz",
        },
        "safety": {
            "main115_oof_alignment": True,
            "main115_val_alignment": True,
            "main133_saved_val_indices_alignment": True,
            "main133_val_reconstruction_max_abs_diff": max_diff,
            "main133_val_reconstruction_mean_abs_diff": mean_diff,
            "main133_reconstruction_tolerance": 1e-5,
            "main133_reconstruction_pass": True,
        },
        "fusion": {
            "main133_dim": LATENT,
            "main115_dim": 5,
            "total_dim": LATENT + 5,
            "lr_C": 0.1,
            "svm_C": 1.0,
            "no_validation_tuning": True,
        },
        "results": {
            "lr_oof_accuracy": float(lr_oof_acc),
            "lr_oof_auc": float(lr_oof_auc),
            "lr_val_accuracy": float(lr_val_acc),
            "lr_val_auc": float(lr_val_auc),
            "svm_oof_accuracy": float(svm_oof_acc),
            "svm_oof_auc": float(svm_oof_auc),
            "svm_val_accuracy": float(svm_val_acc),
            "svm_val_auc": float(svm_val_auc),
            "main115_mean_val_accuracy": float(main115_mean_acc),
            "main115_mean_val_auc": float(main115_mean_auc),
            "main115_frozen_rule_val_accuracy": float(main115_rule_acc),
        },
        "runtime_seconds": time.time() - t0,
    }

    np.savez_compressed(
        ROOT / "main154_results.npz",
        train_indices=tr_idx.astype(np.int64),
        val_indices=va_idx.astype(np.int64),
        y_train=y_train_canonical.astype(np.int64),
        y_val=y[va_idx].astype(np.int64),
        main133_z_oof=z_oof.astype(np.float32),
        main133_z_val=z_val_exact.astype(np.float32),
        main115_p_oof=p115_oof.astype(np.float32),
        main115_p_val=p115_val.astype(np.float32),
        lr_oof_prob=lr_oof_prob.astype(np.float32),
        lr_val_prob=lr_val_prob.astype(np.float32),
        svm_oof_prob=svm_oof_prob.astype(np.float32),
        svm_val_prob=svm_val_prob.astype(np.float32),
    )

    with (ROOT / "main154_report.json").open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print("\nSaved:")
    print(ROOT / "main154_results.npz")
    print(ROOT / "main154_report.json")
    print("Runtime:", time.time() - t0, "sec")


if __name__ == "__main__":
    main()
