#!/usr/bin/env python3
"""
MAIN155 / EXPERIMENT 35
STRICT OOF MAIN131 + MAIN115 FUSION

Purpose
-------
Test whether the Main131 / Exp11 learned representation adds useful
information to the Main115 specialist probabilities under a strict,
leakage-safe fusion protocol.

Main131 is the actual Exp11 architecture:
    word TF-IDF (1-3 grams, 60k features)
        -> Linear(60000, 128) + BN/GELU/Dropout
    structural 62-D features
        -> Linear(62, 128) + BN/GELU/Dropout
    concat 256
        -> Linear(256, 192) + BN/GELU/Dropout
        -> Linear(192, 128) + BN/GELU/Dropout
        -> classifier

Strict OOF protocol:
    - canonical 8428/2108 split is preserved exactly
    - Main115 OOF/VAL probabilities are used as fixed inputs
    - Main131 representation is generated by 5-fold cross-fitting
    - each fold fits TF-IDF and structural scaler only on fold-train
    - each fold trains Main131 for exactly 3 epochs
    - held-out rows are never used to fit that fold's representation
    - validation uses the saved Main131 checkpoint and is never used to
      train/tune the fusion classifier
    - LR and LinearSVC are trained only on the 8428-row strict OOF matrix

No validation tuning.
No Kaggle submission.
"""

import json
import random
import time
from pathlib import Path
import importlib.util

import numpy as np
import torch
import torch.nn as nn

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from torch.utils.data import Dataset, DataLoader


ROOT = Path("/home/manu/Desktop/ML4CPMS/project_1")
TRAIN_PATH = ROOT / "train.json"
MAIN131_CHECKPOINT = ROOT / "main131_best.pt"
MAIN131_EMBEDDINGS = ROOT / "main131_embeddings.npz"
MAIN115_RESULTS = ROOT / "main115_results.npz"

SEED = 155
N_SPLITS = 5
FOLD_EPOCHS = 1
BATCH_SIZE = 64
MAX_FEATURES = 60000
STRUCT_DIM = 62
TFIDF_HIDDEN = 128
STRUCT_HIDDEN = 128
FUSION_HIDDEN = 192
LATENT_DIM = 128
DROPOUT = 0.20
LR = 0.002
WEIGHT_DECAY = 1e-4
MAX_FEATURES = 60000

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
TOL = 1e-5


def seed_all(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_json_or_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        first = None
        for line in f:
            if line.strip():
                first = line.strip()
                break

    if first is None:
        raise ValueError("Dataset is empty.")

    if first.startswith("["):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError as e:
                    raise ValueError(f"Invalid JSON on line {line_no}") from e
    return rows


def label_to_int(x):
    if isinstance(x, str):
        if x.upper() == "A":
            return 0
        if x.upper() == "B":
            return 1
    return int(x)


def tokens_to_string(seq):
    return " ".join(map(str, seq))


def load_main131_module():
    candidates = [
        ROOT / "main131.py",
        ROOT / "main131(1).py",
    ]
    path = next((p for p in candidates if p.exists()), None)
    if path is None:
        raise FileNotFoundError(
            "Could not find main131.py or main131(1).py in project directory."
        )

    spec = importlib.util.spec_from_file_location("main131_reference", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def encode_main131_model(vocab_size, main131):
    model = main131.FusionEncoder(
        tfidf_dim=MAX_FEATURES,
        struct_dim=STRUCT_DIM,
        tfidf_hidden=TFIDF_HIDDEN,
        struct_hidden=STRUCT_HIDDEN,
        fusion_hidden=FUSION_HIDDEN,
        latent_dim=LATENT_DIM,
        dropout=DROPOUT,
    ).to(DEVICE)
    return model


class SparsePairDataset(Dataset):
    """
    Keep TF-IDF sparse until individual samples are fetched. This avoids
    materializing a full 60k-dimensional dense fold matrix in RAM.
    """
    def __init__(self, tfidf_matrix, struct_matrix, labels):
        self.tfidf = tfidf_matrix
        self.struct = np.asarray(struct_matrix, dtype=np.float32)
        self.labels = np.asarray(labels, dtype=np.float32)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        row = self.tfidf[idx].toarray().ravel().astype(np.float32)
        return (
            torch.from_numpy(row),
            torch.from_numpy(self.struct[idx]),
            torch.tensor(self.labels[idx], dtype=torch.float32),
        )


def make_vectorizer():
    return TfidfVectorizer(
        analyzer="word",
        token_pattern=r"(?u)\S+",
        ngram_range=(1, 3),
        min_df=2,
        max_df=0.995,
        max_features=MAX_FEATURES,
        sublinear_tf=True,
        dtype=np.float32,
    )


def build_fold_features(token_lists, fit_idx, query_idx, main131):
    fit_tokens = [token_lists[i] for i in fit_idx]
    query_tokens = [token_lists[i] for i in query_idx]

    fit_strings = [tokens_to_string(s) for s in fit_tokens]
    query_strings = [tokens_to_string(s) for s in query_tokens]

    vectorizer = make_vectorizer()
    X_fit_tfidf = vectorizer.fit_transform(fit_strings)
    X_query_tfidf = vectorizer.transform(query_strings)

    X_fit_struct = np.vstack(
        [main131.sequence_features(s) for s in fit_tokens]
    ).astype(np.float32)
    X_query_struct = np.vstack(
        [main131.sequence_features(s) for s in query_tokens]
    ).astype(np.float32)

    if X_fit_struct.shape[1] != STRUCT_DIM:
        raise RuntimeError(
            f"Expected {STRUCT_DIM} structural features, "
            f"got {X_fit_struct.shape[1]}"
        )

    scaler = StandardScaler()
    X_fit_struct = scaler.fit_transform(X_fit_struct).astype(np.float32)
    X_query_struct = scaler.transform(X_query_struct).astype(np.float32)

    return (
        X_fit_tfidf,
        X_query_tfidf,
        X_fit_struct,
        X_query_struct,
    )


def train_fold_and_predict(
    token_lists,
    labels,
    fit_idx,
    hold_idx,
    main131,
    fold_number,
):
    X_fit_tfidf, X_hold_tfidf, X_fit_struct, X_hold_struct = (
        build_fold_features(token_lists, fit_idx, hold_idx, main131)
    )

    y_fit = labels[fit_idx].astype(np.float32)

    dataset = SparsePairDataset(
        X_fit_tfidf,
        X_fit_struct,
        y_fit,
    )

    loader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    seed_all(SEED + fold_number)
    model = encode_main131_model(X_fit_tfidf.shape[1], main131)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LR,
        weight_decay=WEIGHT_DECAY,
    )

    for epoch in range(1, FOLD_EPOCHS + 1):
        model.train()
        loss_sum = 0.0
        total = 0

        for tfidf, struct, yb in loader:
            tfidf = tfidf.to(DEVICE, non_blocking=True)
            struct = struct.to(DEVICE, non_blocking=True)
            yb = yb.to(DEVICE, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)
            logits = model(tfidf, struct)
            loss = criterion(logits, yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

            loss_sum += float(loss.item()) * len(yb)
            total += len(yb)

        print(
            f"Fold {fold_number} | epoch {epoch}/{FOLD_EPOCHS} | "
            f"train loss {loss_sum / total:.5f}"
        )

    # Holdout inference only.
    model.eval()
    hold_z = []

    hold_ds = SparsePairDataset(
        X_hold_tfidf,
        X_hold_struct,
        np.zeros(len(hold_idx), dtype=np.float32),
    )
    hold_loader = DataLoader(
        hold_ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    with torch.no_grad():
        for tfidf, struct, _ in hold_loader:
            tfidf = tfidf.to(DEVICE, non_blocking=True)
            struct = struct.to(DEVICE, non_blocking=True)
            z = model.encode(tfidf, struct)
            hold_z.append(z.cpu().numpy())

    return np.concatenate(hold_z).astype(np.float32)


def reconstruct_exact_main131_validation(
    token_lists,
    va_idx,
    checkpoint,
    main131,
):
    """
    Reconstruct Main131's saved validation latent exactly enough for the
    1e-5 safety gate.

    Main131 has no SVD. The saved TF-IDF vocabulary/IDF is used directly,
    then the exact saved structural scaler and model weights are applied.
    """
    rows = [token_lists[i] for i in va_idx]
    texts = [tokens_to_string(s) for s in rows]

    saved_vocab = checkpoint["tfidf_vocabulary"]
    saved_idf = np.asarray(checkpoint["tfidf_idf"], dtype=np.float32)

    # Recreate the sparse TF-IDF arithmetic exactly.
    cv = CountVectorizer(
        vocabulary=saved_vocab,
        token_pattern=r"(?u)\S+",
        ngram_range=(1, 3),
        dtype=np.float32,
    )
    X = cv.transform(texts).tocoo(copy=True)

    X.data = (1.0 + np.log(X.data)).astype(np.float32)
    X.data *= saved_idf[X.col]
    X = X.tocsr()

    row_norm = np.sqrt(X.multiply(X).sum(axis=1)).A1
    inv = np.divide(
        1.0,
        row_norm,
        out=np.zeros_like(row_norm),
        where=row_norm > 0,
    )
    X = X.multiply(inv[:, None]).tocsr()

    X_struct = np.vstack(
        [main131.sequence_features(s) for s in rows]
    ).astype(np.float32)

    struct_mean = np.asarray(
        checkpoint["struct_scaler_mean"], dtype=np.float32
    )
    struct_scale = np.asarray(
        checkpoint["struct_scaler_scale"], dtype=np.float32
    )
    X_struct = (
        (X_struct - struct_mean) / struct_scale
    ).astype(np.float32)

    model = main131.FusionEncoder(
        tfidf_dim=int(checkpoint["config"]["tfidf_dim"]),
        struct_dim=int(checkpoint["config"]["struct_dim"]),
        tfidf_hidden=int(checkpoint["config"]["tfidf_hidden"]),
        struct_hidden=int(checkpoint["config"]["struct_hidden"]),
        fusion_hidden=int(checkpoint["config"]["fusion_hidden"]),
        latent_dim=int(checkpoint["config"]["latent_dim"]),
        dropout=float(checkpoint["config"]["dropout"]),
    ).to(DEVICE)

    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    zs = []

    with torch.no_grad():
        for start in range(0, len(rows), BATCH_SIZE):
            tfidf = torch.from_numpy(
                X[start:start + BATCH_SIZE].toarray().astype(np.float32)
            ).to(DEVICE)
            struct = torch.from_numpy(
                X_struct[start:start + BATCH_SIZE]
            ).to(DEVICE)

            z = model.encode(tfidf, struct)
            zs.append(z.cpu().numpy())

    return np.concatenate(zs).astype(np.float32)


def main():
    start_time = time.time()
    seed_all(SEED)

    print("=" * 78)
    print("MAIN155 — STRICT OOF MAIN131 + MAIN115 FUSION")
    print("=" * 78)
    print(f"Device: {DEVICE}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    for p in (
        TRAIN_PATH,
        MAIN131_CHECKPOINT,
        MAIN131_EMBEDDINGS,
        MAIN115_RESULTS,
    ):
        if not p.exists():
            raise FileNotFoundError(f"Missing required artifact: {p}")

    rows = load_json_or_jsonl(TRAIN_PATH)
    token_lists = [list(map(int, r["text"])) for r in rows]
    y = np.asarray(
        [label_to_int(r["label"]) for r in rows],
        dtype=np.int64,
    )

    print(f"Dataset: {len(token_lists)}")

    main131 = load_main131_module()
    print("Loaded Main131 reference implementation.")

    all_idx = np.arange(len(y))
    tr_idx, va_idx = train_test_split(
        all_idx,
        test_size=0.20,
        stratify=y,
        random_state=42,
    )
    tr_idx = np.asarray(tr_idx, dtype=np.int64)
    va_idx = np.asarray(va_idx, dtype=np.int64)

    print(
        f"Canonical train/validation: {len(tr_idx)} {len(va_idx)}"
    )
    print("Canonical validation order preserved: YES")

    # ------------------------------------------------------------------
    # Main115 alignment.
    # ------------------------------------------------------------------
    m115 = np.load(MAIN115_RESULTS, allow_pickle=True)

    y_oof_115 = np.asarray(m115["y_oof"]).astype(np.int64)
    y_val_115 = np.asarray(m115["y_val"]).astype(np.int64)

    if len(y_oof_115) != len(tr_idx):
        raise RuntimeError("Main115 OOF length does not match canonical train.")
    if len(y_val_115) != len(va_idx):
        raise RuntimeError("Main115 VAL length does not match canonical val.")

    if not np.array_equal(y_oof_115, y[tr_idx]):
        raise RuntimeError("Main115 OOF label alignment failed.")
    if not np.array_equal(y_val_115, y[va_idx]):
        raise RuntimeError("Main115 VAL label alignment failed.")

    specialist_oof = np.asarray(
        m115["specialist_p_oof"], dtype=np.float32
    )
    specialist_val = np.asarray(
        m115["specialist_p_val"], dtype=np.float32
    )

    print("Main115 OOF alignment: PASS")
    print("Main115 VAL alignment: PASS")

    # ------------------------------------------------------------------
    # Exact Main131 validation reconstruction safety check.
    # ------------------------------------------------------------------
    checkpoint = torch.load(
        MAIN131_CHECKPOINT,
        map_location="cpu",
        weights_only=False,
    )

    saved = np.load(MAIN131_EMBEDDINGS, allow_pickle=True)
    saved_va_idx = np.asarray(saved["val_indices"]).astype(np.int64)
    saved_z_val = np.asarray(saved["z_val"]).astype(np.float32)

    if not np.array_equal(saved_va_idx, va_idx):
        raise RuntimeError(
            "FAIL: saved Main131 validation indices do not match canonical "
            "validation order."
        )

    print("\nReconstructing exact Main131 validation latent...")
    z_val_exact = reconstruct_exact_main131_validation(
        token_lists,
        va_idx,
        checkpoint,
        main131,
    )

    max_diff = float(np.max(np.abs(z_val_exact - saved_z_val)))
    mean_diff = float(np.mean(np.abs(z_val_exact - saved_z_val)))

    print("Main131 z_val max abs diff :", max_diff)
    print("Main131 z_val mean abs diff:", mean_diff)
    print("Safety tolerance           :", TOL)

    if max_diff >= TOL:
        raise RuntimeError(
            "FAIL: Main131 validation reconstruction exceeds 1e-5. "
            "Do not continue to fusion."
        )

    print("Main131 validation reconstruction: PASS")

    # ------------------------------------------------------------------
    # Strict 5-fold OOF Main131 representation.
    # ------------------------------------------------------------------
    print("\nStarting strict 5-fold Main131 OOF generation...")

    skf = StratifiedKFold(
        n_splits=N_SPLITS,
        shuffle=True,
        random_state=SEED,
    )

    z_oof = np.zeros(
        (len(tr_idx), LATENT_DIM),
        dtype=np.float32,
    )

    y_train_canonical = y[tr_idx]

    for fold_number, (fit_pos, hold_pos) in enumerate(
        skf.split(tr_idx, y_train_canonical),
        start=1,
    ):
        fit_idx = tr_idx[fit_pos]
        hold_idx = tr_idx[hold_pos]

        print("\n" + "-" * 70)
        print(
            f"FOLD {fold_number}/{N_SPLITS} | "
            f"fit={len(fit_idx)} holdout={len(hold_idx)}"
        )

        z_hold = train_fold_and_predict(
            token_lists,
            y,
            fit_idx,
            hold_idx,
            main131,
            fold_number,
        )

        z_oof[hold_pos] = z_hold

    if not np.all(np.isfinite(z_oof)):
        raise RuntimeError("Strict OOF z contains non-finite values.")

    print("\nStrict Main131 OOF generation: PASS")
    print("z_oof shape:", z_oof.shape)

    # ------------------------------------------------------------------
    # Strict OOF fusion.
    # ------------------------------------------------------------------
    X_fusion_oof = np.hstack(
        [z_oof, specialist_oof]
    ).astype(np.float32)

    X_fusion_val = np.hstack(
        [z_val_exact, specialist_val]
    ).astype(np.float32)

    print("Fusion train shape:", X_fusion_oof.shape)
    print("Fusion validation shape:", X_fusion_val.shape)

    lr_fusion = LogisticRegression(
        C=0.1,
        class_weight="balanced",
        max_iter=3000,
        random_state=SEED,
    )
    lr_fusion.fit(X_fusion_oof, y_oof_115)

    lr_oof_prob = lr_fusion.predict_proba(X_fusion_oof)[:, 1]
    lr_val_prob = lr_fusion.predict_proba(X_fusion_val)[:, 1]

    lr_oof_pred = (lr_oof_prob >= 0.5).astype(np.int64)
    lr_val_pred = (lr_val_prob >= 0.5).astype(np.int64)

    lr_oof_acc = accuracy_score(y_oof_115, lr_oof_pred)
    lr_val_acc = accuracy_score(y_val_115, lr_val_pred)
    lr_oof_auc = roc_auc_score(y_oof_115, lr_oof_prob)
    lr_val_auc = roc_auc_score(y_val_115, lr_val_prob)

    print("\n=== STRICT OOF LOGISTIC REGRESSION FUSION ===")
    print(f"OOF accuracy: {lr_oof_acc}")
    print(f"OOF AUC     : {lr_oof_auc}")
    print(f"VAL accuracy: {lr_val_acc}")
    print(f"VAL AUC     : {lr_val_auc}")

    svm_fusion = LinearSVC(
        C=1.0,
        class_weight="balanced",
        random_state=SEED,
    )
    svm_fusion.fit(X_fusion_oof, y_oof_115)

    svm_oof_score = svm_fusion.decision_function(X_fusion_oof)
    svm_val_score = svm_fusion.decision_function(X_fusion_val)

    svm_oof_pred = (svm_oof_score >= 0.0).astype(np.int64)
    svm_val_pred = (svm_val_score >= 0.0).astype(np.int64)

    svm_oof_acc = accuracy_score(y_oof_115, svm_oof_pred)
    svm_val_acc = accuracy_score(y_val_115, svm_val_pred)
    svm_oof_auc = roc_auc_score(y_oof_115, svm_oof_score)
    svm_val_auc = roc_auc_score(y_val_115, svm_val_score)

    print("\n=== STRICT OOF LINEAR SVM FUSION ===")
    print(f"OOF accuracy: {svm_oof_acc}")
    print(f"OOF AUC     : {svm_oof_auc}")
    print(f"VAL accuracy: {svm_val_acc}")
    print(f"VAL AUC     : {svm_val_auc}")

    # Main115 references.
    mean_specialist_val = specialist_val.mean(axis=1)
    mean_specialist_pred = (
        mean_specialist_val >= 0.5
    ).astype(np.int64)

    mean_specialist_acc = accuracy_score(
        y_val_115,
        mean_specialist_pred,
    )
    mean_specialist_auc = roc_auc_score(
        y_val_115,
        mean_specialist_val,
    )

    # Reproduce the frozen Main115 consensus rule from its saved artifact.
    frozen_consensus = None
    if "corrected_val" in m115.files:
        frozen_consensus = np.asarray(
            m115["corrected_val"]
        ).astype(np.int64)
    elif "teacher_val" in m115.files:
        frozen_consensus = np.asarray(
            m115["teacher_val"]
        ).astype(np.int64)
    else:
        raise RuntimeError(
            "Main115 artifact contains neither corrected_val nor teacher_val."
        )

    frozen_acc = accuracy_score(
        y_val_115,
        frozen_consensus,
    )

    print("\n=== MAIN115 REFERENCES ===")
    print(f"Specialist mean VAL accuracy: {mean_specialist_acc}")
    print(f"Specialist mean VAL AUC     : {mean_specialist_auc}")
    print(f"Frozen consensus VAL accuracy: {frozen_acc}")

    runtime = time.time() - start_time

    report = {
        "experiment": "Main155 / Phase9 Exp35",
        "description": (
            "Strict 5-fold OOF fusion of Main131 learned representation "
            "with Main115 specialist probabilities."
        ),
        "seed": SEED,
        "device": str(DEVICE),
        "dataset_size": int(len(y)),
        "canonical_train_size": int(len(tr_idx)),
        "canonical_val_size": int(len(va_idx)),
        "canonical_split": {
            "method": "train_test_split",
            "test_size": 0.2,
            "stratify": True,
            "random_state": 42,
            "order_preserved": True,
        },
        "strict_ooo": {
            "folds": N_SPLITS,
            "fold_seed": SEED,
            "main131_fold_epochs": FOLD_EPOCHS,
            "main131_fit_only_on_fold_train": True,
            "main115_source": "main115_results.npz",
        },
        "safety": {
            "main115_oof_alignment": True,
            "main115_val_alignment": True,
            "main131_saved_val_indices_alignment": True,
            "main131_val_reconstruction_max_abs_diff": max_diff,
            "main131_val_reconstruction_mean_abs_diff": mean_diff,
            "main131_reconstruction_tolerance": TOL,
            "main131_reconstruction_pass": True,
        },
        "fusion": {
            "main131_dim": LATENT_DIM,
            "main115_dim": int(specialist_oof.shape[1]),
            "total_dim": int(X_fusion_oof.shape[1]),
            "lr_C": 0.1,
            "svm_C": 1.0,
            "no_validation_tuning": True,
        },
        "results": {
            "lr_oof_accuracy": float(lr_oof_acc),
            "lr_oof_auc": float(lr_oof_auc),
            "lr_val_accuracy": float(lr_val_acc),
            "lr_val_auc": float(lr_val_auc),
            "svm_oof_accuracy": float(svm_oof_acc),
            "svm_oof_auc": float(svm_oof_auc),
            "svm_val_accuracy": float(svm_val_acc),
            "svm_val_auc": float(svm_val_auc),
            "main115_mean_val_accuracy": float(mean_specialist_acc),
            "main115_mean_val_auc": float(mean_specialist_auc),
            "main115_frozen_rule_val_accuracy": float(frozen_acc),
        },
        "runtime_seconds": float(runtime),
    }

    np.savez_compressed(
        ROOT / "main155_results.npz",
        z_oof=z_oof,
        z_val=z_val_exact,
        y_oof=y_oof_115,
        y_val=y_val_115,
        specialist_p_oof=specialist_oof,
        specialist_p_val=specialist_val,
        lr_oof_prob=lr_oof_prob,
        lr_val_prob=lr_val_prob,
        svm_oof_score=svm_oof_score,
        svm_val_score=svm_val_score,
        lr_val_pred=lr_val_pred,
        svm_val_pred=svm_val_pred,
    )

    with open(ROOT / "main155_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print("\n=== MAIN155 SUMMARY ===")
    print(f"LR  strict OOF fusion VAL accuracy : {lr_val_acc:.6f}")
    print(f"LR  strict OOF fusion VAL AUC      : {lr_val_auc:.6f}")
    print(f"SVM strict OOF fusion VAL accuracy : {svm_val_acc:.6f}")
    print(f"SVM strict OOF fusion VAL AUC      : {svm_val_auc:.6f}")
    print(f"Main115 frozen rule VAL accuracy   : {frozen_acc:.6f}")

    print("\nSaved:")
    print(ROOT / "main155_results.npz")
    print(ROOT / "main155_report.json")
    print(f"Runtime: {runtime:.3f} sec")


if __name__ == "__main__":
    main()
