#!/usr/bin/env python3
"""
MAIN79
======

Final submission candidate:
    Main66 classical teacher
        +
    Main78-style neural residual ensemble

Important:
- The classical teacher used for the neural training targets is leakage-safe:
  Main64 OOF meta-features are used for the 8428 training rows and the
  held-out 2108 validation meta-features are used for the remaining rows.
- The test teacher is rebuilt from Main66's exact full-data classical pipeline.
- The residual branch is deliberately small and its final contribution is
  fixed at the conservative 0.025 weight validated in Main78.
- Three residual BiGRUs are trained and averaged, matching the useful
  Main78 ensemble idea.
- No validation score is invented here; this script's job is to produce
  submission_main79.csv.

Required files in this folder:
    train.json
    test.json
    main66.py
    main64_oof_meta_features.npy
    main64_val_meta_features.npy

Also required:
    main64_oof_svm.npy
    main64_oof_nbsvm.npy
    main64_oof_hgb.npy
    main64_oof_local.npy

The script does NOT modify train/test data.
"""

import os
import json
import time
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

warnings.filterwarnings("ignore")

# ============================================================
# CONFIG
# ============================================================

SEED = 42
MODEL_SEEDS = [42, 123, 777]

BATCH_SIZE = 32
MAX_LEN = 384

# Main78 used 9 epochs and early stopping. For full-data training
# there is no held-out validation, so use a fixed conservative point
# covering the empirically useful Main78 range.
EPOCHS = 6

LR = 3e-4
WEIGHT_DECAY = 1e-3
GRAD_CLIP = 1.0
NUM_WORKERS = 0

EMB_DIM = 64
HIDDEN = 64
DROPOUT = 0.40

# Main78 validation:
# teacher 0.928368
# residual ensemble + weight 0.025 -> 0.937381
RESIDUAL_WEIGHT = 0.025

META_C = 0.1

PROJECT = Path(__file__).resolve().parent

TRAIN_FILE = PROJECT / "train.json"
TEST_FILE = PROJECT / "test.json"

OOF_META_FILE = PROJECT / "main64_oof_meta_features.npy"
VAL_META_FILE = PROJECT / "main64_val_meta_features.npy"

OOF_SVM_FILE = PROJECT / "main64_oof_svm.npy"
OOF_NBSVM_FILE = PROJECT / "main64_oof_nbsvm.npy"
OOF_HGB_FILE = PROJECT / "main64_oof_hgb.npy"
OOF_LOCAL_FILE = PROJECT / "main64_oof_local.npy"

SUBMISSION_FILE = PROJECT / "submission_main79.csv"
OUT_DIR = PROJECT / "main79_outputs"
OUT_DIR.mkdir(exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
USE_AMP = DEVICE.type == "cuda"


# ============================================================
# REPRODUCIBILITY
# ============================================================

def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = True


# ============================================================
# LOAD DATA
# ============================================================

def load_jsonl(path, labelled=True):
    rows = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))

    texts = [r["text"] for r in rows]
    ids = [r["id"] for r in rows]

    if labelled:
        labels = np.asarray(
            [0 if r["label"] == "A" else 1 for r in rows],
            dtype=np.int64
        )
        return ids, texts, labels

    return ids, texts


# ============================================================
# SAFE MAIN64 META TEACHER
# ============================================================

def reconstruct_safe_teacher(texts, labels):
    """
    Main64 OOF meta features cover the 8428 training split.
    Main64 validation meta features cover the remaining 2108 rows.

    For every row, its stored base-model features were generated by a model
    that did not train on that row. We therefore have a leakage-safe teacher
    score for all 10536 labelled examples.
    """

    n = len(labels)

    idx = np.arange(n)

    train_idx, val_idx = train_test_split(
        idx,
        test_size=0.20,
        random_state=SEED,
        stratify=labels
    )

    oof_meta = np.load(OOF_META_FILE).astype(np.float32)
    val_meta = np.load(VAL_META_FILE).astype(np.float32)

    print("OOF meta:", oof_meta.shape)
    print("VAL meta:", val_meta.shape)

    if oof_meta.shape[0] != len(train_idx):
        raise RuntimeError(
            f"OOF meta has {oof_meta.shape[0]} rows, expected {len(train_idx)}."
        )

    if val_meta.shape[0] != len(val_idx):
        raise RuntimeError(
            f"VAL meta has {val_meta.shape[0]} rows, expected {len(val_idx)}."
        )

    if oof_meta.shape[1] != 13:
        raise RuntimeError(
            f"Expected 13 meta features, got {oof_meta.shape[1]}."
        )

    if val_meta.shape[1] != 13:
        raise RuntimeError(
            f"Expected 13 validation meta features, got {val_meta.shape[1]}."
        )

    # Exact Main66/Main78 meta learner.
    meta_model = LogisticRegression(
        C=META_C,
        max_iter=5000,
        solver="lbfgs",
        random_state=SEED
    )

    meta_model.fit(
        oof_meta,
        labels[train_idx]
    )

    teacher_train_raw = meta_model.decision_function(
        oof_meta
    ).astype(np.float32)

    teacher_val_raw = meta_model.decision_function(
        val_meta
    ).astype(np.float32)

    # Put both parts back into original dataset order.
    teacher_raw_all = np.empty(n, dtype=np.float32)
    teacher_raw_all[train_idx] = teacher_train_raw
    teacher_raw_all[val_idx] = teacher_val_raw

    # Same robust score scaling used by Main78.
    teacher_scale = np.percentile(
        np.abs(teacher_train_raw),
        95
    )

    if teacher_scale < 1e-6:
        teacher_scale = 1.0

    teacher_all = np.clip(
        teacher_raw_all / teacher_scale,
        -6.0,
        6.0
    ).astype(np.float32)

    # Same feature normalization convention used by Main78.
    meta_mean = np.mean(oof_meta, axis=0)
    meta_std = np.std(oof_meta, axis=0)
    meta_std = np.where(
        meta_std < 1e-6,
        1.0,
        meta_std
    )

    meta_all = np.empty_like(
        teacher_all[:, None],
        shape=(n, 13)
    )

    meta_all[train_idx] = np.clip(
        (oof_meta - meta_mean) / meta_std,
        -6.0,
        6.0
    )

    meta_all[val_idx] = np.clip(
        (val_meta - meta_mean) / meta_std,
        -6.0,
        6.0
    )

    # Useful sanity information.
    val_pred = (teacher_val_raw >= 0).astype(np.int64)
    val_acc = np.mean(val_pred == labels[val_idx])

    print(f"Reconstructed Main78 teacher validation accuracy: {val_acc:.6f}")
    print(f"Teacher raw scale: {teacher_scale:.6f}")
    print(
        "Teacher raw range:",
        float(teacher_raw_all.min()),
        float(teacher_raw_all.max())
    )

    return (
        train_idx,
        val_idx,
        meta_model,
        teacher_scale,
        meta_mean,
        meta_std,
        teacher_all,
        meta_all
    )


# ============================================================
# RESIDUAL DATASET
# ============================================================

class ResidualDataset(Dataset):
    def __init__(self, seqs, labels, meta_z):
        self.seqs = seqs
        self.labels = np.asarray(labels, dtype=np.float32)
        self.meta_z = np.asarray(meta_z, dtype=np.float32)

    def __len__(self):
        return len(self.seqs)

    def __getitem__(self, i):
        x = np.asarray(
            self.seqs[i],
            dtype=np.int64
        )

        if len(x) > MAX_LEN:
            x = x[:MAX_LEN]

        n = len(x)

        # Main78 convention:
        # PAD_IDX is one ID above the largest real token ID.
        ids = np.full(
            MAX_LEN,
            PAD_IDX,
            dtype=np.int64
        )

        mask = np.zeros(
            MAX_LEN,
            dtype=np.bool_
        )

        ids[:n] = x
        mask[:n] = True

        unique_ratio = (
            len(np.unique(x)) /
            max(n, 1)
        )

        repeat_ratio = 1.0 - unique_ratio
        length_log = np.log1p(n) / 7.0

        aux = np.concatenate([
            self.meta_z[i],
            np.asarray([
                unique_ratio,
                repeat_ratio,
                length_log
            ], dtype=np.float32)
        ]).astype(np.float32)

        return (
            torch.from_numpy(ids),
            torch.from_numpy(mask),
            torch.tensor(self.labels[i]),
            torch.from_numpy(aux)
        )


# ============================================================
# MODEL — MAIN78 ARCHITECTURE
# ============================================================

class ResidualBiGRU(nn.Module):
    def __init__(self, meta_dim):
        super().__init__()

        self.embedding = nn.Embedding(
            VOCAB_SIZE + 1,
            EMB_DIM,
            padding_idx=PAD_IDX
        )

        self.gru = nn.GRU(
            input_size=EMB_DIM,
            hidden_size=HIDDEN,
            num_layers=1,
            batch_first=True,
            bidirectional=True
        )

        enc_dim = 2 * HIDDEN
        pooled_dim = 3 * enc_dim

        self.attn = nn.Sequential(
            nn.Linear(enc_dim, 32),
            nn.Tanh(),
            nn.Linear(32, 1)
        )

        self.neural_proj = nn.Sequential(
            nn.Linear(pooled_dim, 64),
            nn.LayerNorm(64),
            nn.ReLU(),
            nn.Dropout(DROPOUT)
        )

        self.meta_proj = nn.Sequential(
            nn.Linear(meta_dim + 3, 32),
            nn.LayerNorm(32),
            nn.ReLU(),
            nn.Dropout(DROPOUT)
        )

        self.head = nn.Sequential(
            nn.Linear(96, 48),
            nn.ReLU(),
            nn.Dropout(DROPOUT),
            nn.Linear(48, 1)
        )

    def forward(self, ids, mask, aux):
        e = self.embedding(ids)

        h, _ = self.gru(e)

        mask_f = mask.unsqueeze(-1)

        denom = mask_f.sum(
            dim=1
        ).clamp_min(1)

        mean_pool = (
            h * mask_f
        ).sum(dim=1) / denom

        max_pool = h.masked_fill(
            ~mask_f,
            -1e4
        ).max(dim=1).values

        # Keep attention scores/pooling in FP32.
        # This avoids the FP16 overflow issue encountered in Main74.
        scores = self.attn(
            h.float()
        ).squeeze(-1)

        scores = scores.masked_fill(
            ~mask,
            -1e4
        )

        weights = torch.softmax(
            scores,
            dim=1
        )

        attn_pool = torch.sum(
            h.float() * weights.unsqueeze(-1),
            dim=1
        )

        pooled = torch.cat([
            mean_pool.float(),
            max_pool.float(),
            attn_pool
        ], dim=1)

        neural_z = self.neural_proj(
            pooled
        )

        meta_z = self.meta_proj(
            aux.float()
        )

        z = torch.cat([
            neural_z,
            meta_z
        ], dim=1)

        residual = self.head(
            z
        ).squeeze(-1)

        return residual


def autocast_context():
    if USE_AMP:
        return torch.autocast(
            device_type="cuda",
            dtype=torch.float16
        )

    return torch.autocast(
        device_type="cpu",
        enabled=False
    )


# ============================================================
# TRAIN ONE FULL-DATA RESIDUAL MODEL
# ============================================================

def train_one_seed(
    seed,
    train_loader,
    meta_dim
):
    print("\n" + "=" * 72)
    print(f"TRAINING MAIN79 RESIDUAL — SEED {seed}")
    print("=" * 72)

    seed_everything(seed)

    model = ResidualBiGRU(
        meta_dim
    ).to(DEVICE)

    print(
        "Parameters:",
        sum(
            p.numel()
            for p in model.parameters()
            if p.requires_grad
        )
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LR,
        weight_decay=WEIGHT_DECAY
    )

    criterion = nn.BCEWithLogitsLoss()

    scaler = torch.amp.GradScaler(
        "cuda",
        enabled=USE_AMP
    )

    # Main78 found 0.075 useful during training.
    # The final test-time residual is subsequently shrunk to 0.025.
    TRAIN_WEIGHT = 0.075

    for epoch in range(1, EPOCHS + 1):
        model.train()

        loss_sum = 0.0
        total = 0
        correct = 0

        t0 = time.time()

        for batch_i, (
            ids,
            mask,
            y,
            aux
        ) in enumerate(
            train_loader,
            1
        ):
            ids = ids.to(
                DEVICE,
                non_blocking=True
            )

            mask = mask.to(
                DEVICE,
                non_blocking=True
            )

            y = y.to(
                DEVICE,
                non_blocking=True
            )

            aux = aux.to(
                DEVICE,
                non_blocking=True
            )

            optimizer.zero_grad(
                set_to_none=True
            )

            with autocast_context():
                residual = model(
                    ids,
                    mask,
                    aux
                )

                # aux[:, 0] is the normalized classical teacher.
                teacher = aux[:, 0]

                final_logit = (
                    teacher +
                    TRAIN_WEIGHT * residual
                )

                loss = criterion(
                    final_logit,
                    y
                )

            if not torch.isfinite(loss):
                print(
                    "WARNING: non-finite loss; skipping batch"
                )
                continue

            scaler.scale(
                loss
            ).backward()

            scaler.unscale_(
                optimizer
            )

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                GRAD_CLIP
            )

            scaler.step(
                optimizer
            )

            scaler.update()

            pred = (
                final_logit.detach() >= 0
            ).long()

            correct += int(
                (pred == y.long()).sum().item()
            )

            total += len(y)

            loss_sum += (
                float(loss.item()) *
                len(y)
            )

        train_acc = (
            correct /
            max(total, 1)
        )

        avg_loss = (
            loss_sum /
            max(total, 1)
        )

        print(
            f"epoch {epoch:02d}/{EPOCHS} | "
            f"train_acc={train_acc:.5f} | "
            f"loss={avg_loss:.5f} | "
            f"time={(time.time()-t0)/60:.2f} min"
        )

    path = OUT_DIR / f"main79_residual_seed{seed}.pt"

    torch.save(
        model.state_dict(),
        path
    )

    print("Saved:", path)

    return model


# ============================================================
# PREDICT RESIDUALS
# ============================================================

@torch.no_grad()
def predict_residual(
    model,
    seqs,
    meta_z,
    teacher
):
    model.eval()

    dummy_labels = np.zeros(
        len(seqs),
        dtype=np.float32
    )

    ds = ResidualDataset(
        seqs,
        dummy_labels,
        meta_z
    )

    loader = DataLoader(
        ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=(DEVICE.type == "cuda")
    )

    residuals = []

    for (
        ids,
        mask,
        _,
        aux
    ) in loader:
        ids = ids.to(
            DEVICE,
            non_blocking=True
        )

        mask = mask.to(
            DEVICE,
            non_blocking=True
        )

        aux = aux.to(
            DEVICE,
            non_blocking=True
        )

        with autocast_context():
            r = model(
                ids,
                mask,
                aux
            )

        residuals.append(
            r.float().cpu().numpy()
        )

    return np.concatenate(
        residuals
    ).astype(np.float32)


# ============================================================
# MAIN
# ============================================================

def main():
    global VOCAB_SIZE
    global PAD_IDX

    start = time.time()

    seed_everything(SEED)

    print("=" * 72)
    print("MAIN79 — MAIN66 TEACHER + MAIN78 RESIDUAL ENSEMBLE")
    print("=" * 72)
    print("Device:", DEVICE)

    if torch.cuda.is_available():
        print(
            "GPU:",
            torch.cuda.get_device_name(0)
        )

    # --------------------------------------------------------
    # Check files
    # --------------------------------------------------------

    required = [
        TRAIN_FILE,
        TEST_FILE,
        OOF_META_FILE,
        VAL_META_FILE,
        OOF_SVM_FILE,
        OOF_NBSVM_FILE,
        OOF_HGB_FILE,
        OOF_LOCAL_FILE,
        PROJECT / "main66.py"
    ]

    missing = [
        str(p)
        for p in required
        if not p.exists()
    ]

    if missing:
        raise FileNotFoundError(
            "Missing required files:\n" +
            "\n".join(missing)
        )

    # --------------------------------------------------------
    # Load data
    # --------------------------------------------------------

    train_ids, texts, labels = load_jsonl(
        TRAIN_FILE,
        labelled=True
    )

    test_ids, test_texts = load_jsonl(
        TEST_FILE,
        labelled=False
    )

    print(
        "Train:",
        len(texts),
        "| Test:",
        len(test_texts)
    )

    if len(texts) != 10536:
        print(
            "WARNING: expected 10536 training rows."
        )

    if len(test_texts) != 3000:
        print(
            "WARNING: expected 3000 test rows."
        )

    # --------------------------------------------------------
    # Reconstruct leakage-safe teacher
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 1 — RECONSTRUCT SAFE MAIN64 META TEACHER")
    print("=" * 72)

    (
        train_idx,
        val_idx,
        meta_model,
        teacher_scale,
        meta_mean,
        meta_std,
        teacher_all,
        meta_all
    ) = reconstruct_safe_teacher(
        texts,
        labels
    )

    # --------------------------------------------------------
    # Vocabulary
    # --------------------------------------------------------

    VOCAB_SIZE = (
        max(
            int(t)
            for s in texts
            for t in s
        ) + 1
    )

    PAD_IDX = VOCAB_SIZE

    print("Vocabulary size:", VOCAB_SIZE)
    print("PAD index:", PAD_IDX)

    # --------------------------------------------------------
    # Full-data residual training
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 2 — TRAIN 3 MAIN78-STYLE RESIDUAL MODELS")
    print("=" * 72)

    train_ds = ResidualDataset(
        texts,
        labels,
        meta_all
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=(DEVICE.type == "cuda")
    )

    models = []

    for seed in MODEL_SEEDS:
        model = train_one_seed(
            seed,
            train_loader,
            meta_all.shape[1]
        )
        models.append(model)

    # --------------------------------------------------------
    # Build EXACT Main66 full-data classical test teacher
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 3 — BUILD FULL-DATA MAIN66 TEST TEACHER")
    print("=" * 72)

    # main66.py contains the exact tested representation/base-model
    # implementation. Import it rather than reimplementing a subtly
    # different version here.
    import sys
    sys.path.insert(0, str(PROJECT))

    import main66 as main66

    # Exact Main66 representation on all labelled documents.
    (
        all_strings,
        all_transitions,
        full_tfidf,
        full_trans_vectorizer,
        full_compact_scaler,
        X_all_tfidf,
        X_all_compact,
        X_all_global
    ) = main66.fit_global_representation(
        texts
    )

    (
        test_strings,
        test_transitions,
        X_test_tfidf,
        X_test_compact,
        X_test_global
    ) = main66.transform_global_representation(
        test_texts,
        full_tfidf,
        full_trans_vectorizer,
        full_compact_scaler
    )

    print(
        "Full global matrix:",
        X_all_global.shape
    )

    print(
        "Test global matrix:",
        X_test_global.shape
    )

    # Exact Main66 base scores.
    print("Training final SVM...")
    test_svm = main66.train_svm(
        X_all_global,
        labels,
        X_test_global
    )

    print("Training final NB-SVM...")
    test_nbsvm = main66.train_nbsvm(
        all_strings,
        labels,
        test_strings
    )

    print("Training final HGB...")
    test_hgb = main66.train_hgb(
        X_all_compact,
        labels,
        X_test_compact
    )

    print("Computing final local geometry...")
    test_local = main66.local_geometry_features(
        X_all_tfidf,
        labels,
        X_test_tfidf,
        k=main66.LOCAL_K
    )

    # Exact Main66 meta scaler reconstructed from saved OOF raw scores.
    oof_svm = np.load(
        OOF_SVM_FILE
    ).reshape(-1)

    oof_nbsvm = np.load(
        OOF_NBSVM_FILE
    ).reshape(-1)

    oof_hgb = np.load(
        OOF_HGB_FILE
    ).reshape(-1)

    oof_local = np.load(
        OOF_LOCAL_FILE
    )

    if oof_local.ndim == 1:
        oof_local = oof_local[:, None]

    # Main66 convention: local features are A-positive, so invert.
    oof_local_b = -oof_local

    oof_raw = np.column_stack([
        oof_svm,
        oof_nbsvm,
        oof_hgb,
        oof_local_b[:, 0],
        oof_local_b[:, 1],
        oof_local_b[:, 2],
        oof_local_b[:, 3],
        oof_local_b[:, 6],
        oof_local_b[:, 7],
        oof_local_b[:, 8],
        oof_local_b[:, 9],
        oof_local_b[:, 10]
    ])

    from sklearn.preprocessing import StandardScaler

    exact_meta_scaler = StandardScaler()
    exact_meta_scaler.fit(
        oof_raw
    )

    # Verify exact reconstruction.
    oof_meta_check = np.load(
        OOF_META_FILE
    ).astype(np.float32)

    reconstructed = exact_meta_scaler.transform(
        oof_raw
    )

    max_diff = np.max(
        np.abs(
            reconstructed -
            oof_meta_check[:, :12]
        )
    )

    print(
        "Main64 meta reconstruction max diff:",
        float(max_diff)
    )

    if max_diff > 1e-5:
        raise RuntimeError(
            "Main64 meta-feature reconstruction failed. "
            "Stopping before generating submission."
        )

    # Exact Main66 test meta features.
    test_meta = main66.make_meta_features(
        test_svm,
        test_nbsvm,
        test_hgb,
        test_local,
        exact_meta_scaler
    ).astype(np.float32)

    if test_meta.shape[1] != 13:
        raise RuntimeError(
            f"Expected 13 test meta features, got {test_meta.shape}."
        )

    # Meta model from Main64 OOF features.
    oof_meta = np.load(
        OOF_META_FILE
    ).astype(np.float32)

    meta_model = LogisticRegression(
        C=META_C,
        max_iter=5000,
        solver="lbfgs",
        random_state=SEED
    )

    meta_model.fit(
        oof_meta,
        labels[train_idx]
    )

    test_teacher_raw = meta_model.decision_function(
        test_meta
    ).astype(np.float32)

    test_teacher = np.clip(
        test_teacher_raw / teacher_scale,
        -6.0,
        6.0
    ).astype(np.float32)

    # Main78-style normalization for the neural auxiliary meta features.
    test_meta_z = np.clip(
        (test_meta - meta_mean) / meta_std,
        -6.0,
        6.0
    ).astype(np.float32)

    print(
        "Test teacher range:",
        float(test_teacher.min()),
        float(test_teacher.max())
    )

    # --------------------------------------------------------
    # Residual ensemble
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 4 — PREDICT RESIDUAL ENSEMBLE")
    print("=" * 72)

    all_residuals = []

    for seed, model in zip(
        MODEL_SEEDS,
        models
    ):
        print(
            f"Predicting residual — seed {seed}"
        )

        r = predict_residual(
            model,
            test_texts,
            test_meta_z,
            test_teacher
        )

        all_residuals.append(
            r
        )

    residual_matrix = np.vstack(
        all_residuals
    )

    residual_mean = np.mean(
        residual_matrix,
        axis=0
    ).astype(np.float32)

    print(
        "Residual mean/std:",
        float(residual_mean.mean()),
        float(residual_mean.std())
    )

    # Conservative Main78 blend.
    final_score = (
        test_teacher +
        RESIDUAL_WEIGHT * residual_mean
    )

    prediction = (
        final_score >= 0
    ).astype(np.int64)

    labels_out = np.where(
        prediction == 0,
        "A",
        "B"
    )

    # --------------------------------------------------------
    # Sanity checks
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 5 — SANITY CHECKS")
    print("=" * 72)

    if len(prediction) != len(test_ids):
        raise RuntimeError(
            "Prediction/test-ID length mismatch."
        )

    if not np.all(
        np.isfinite(final_score)
    ):
        raise RuntimeError(
            "Final scores contain NaN/Inf."
        )

    if len(np.unique(test_ids)) != len(test_ids):
        raise RuntimeError(
            "Test IDs are not unique."
        )

    if not set(labels_out).issubset({
        "A",
        "B"
    }):
        raise RuntimeError(
            "Invalid labels."
        )

    print(
        "Rows:",
        len(prediction)
    )

    print(
        "A:",
        int(np.sum(labels_out == "A"))
    )

    print(
        "B:",
        int(np.sum(labels_out == "B"))
    )

    # --------------------------------------------------------
    # Submission
    # --------------------------------------------------------

    print("\n" + "=" * 72)
    print("STEP 6 — WRITE SUBMISSION")
    print("=" * 72)

    submission = pd.DataFrame({
        "id": test_ids,
        "label": labels_out
    })

    submission.to_csv(
        SUBMISSION_FILE,
        index=False
    )

    # Re-read and verify.
    check = pd.read_csv(
        SUBMISSION_FILE
    )

    if len(check) != len(test_ids):
        raise RuntimeError(
            "Written submission row count is wrong."
        )

    if list(check.columns) != [
        "id",
        "label"
    ]:
        raise RuntimeError(
            f"Unexpected columns: {list(check.columns)}"
        )

    if not check["id"].is_unique:
        raise RuntimeError(
            "Submission IDs are not unique."
        )

    if not set(
        check["label"].unique()
    ).issubset({
        "A",
        "B"
    }):
        raise RuntimeError(
            "Submission contains labels other than A/B."
        )

    # Save diagnostic arrays as well.
    np.save(
        OUT_DIR / "test_teacher.npy",
        test_teacher
    )

    np.save(
        OUT_DIR / "test_residual_mean.npy",
        residual_mean
    )

    np.save(
        OUT_DIR / "test_final_score.npy",
        final_score
    )

    print()
    print("SUBMISSION CREATED SUCCESSFULLY")
    print("File:", SUBMISSION_FILE)
    print("Rows:", len(check))
    print("Columns:", list(check.columns))
    print(
        "A:",
        int(np.sum(check["label"] == "A"))
    )
    print(
        "B:",
        int(np.sum(check["label"] == "B"))
    )

    print(
        "\nTotal time: "
        f"{time.time() - start:.1f} seconds"
    )

    print("\nMain79 is ready for Kaggle.")


if __name__ == "__main__":
    main()
